###
POST http://localhost:80/users HTTP/1.1
Content-Type: application/json

{
    "name" : "ddavia ",
    "age" : "22",
    "email" : "daviddds@gmail.com",
    "contraseña" : "david"
}

###
GET http://localhost:80/users HTTP/1.1

###

GET http://localhost:80/users/6296c7042395b396210e2a1e HTTP/1.1

###

PUT http://localhost:80/users/6296c73425d1477eed2be51d HTTP/1.1
Content-Type: application/json

{
    "name" : "DirkHC ",
    "age" : "25",
    "email" : "dirkhc@gmail.com",
    "contraseña" : "dirk"
}

###

DELETE http://localhost:80/users/629803151391c4eae488ac97 HTTP/1.1
